import {Queue, Worker, QueueEvents, Job} from 'bullmq'
import Ioredis from 'ioredis'
import { Task, TaskHandler, TaskRegistry, TaskResult } from '../types/types'
import { TaskSchema } from '../types/types'
import {v4 as uuidv4} from 'uuid'